class Tokens:
    SETTINGS = "settings"
    LOGGER = "logger"
    REQUIREMENT_EXTRACTOR = "requirement_extractor"
    NARRATIVE_RULE_SYNTHESIZER = "narrative_rule_synthesizer"
    NORM_RULE_PACK_LOADER = "norm_rule_pack_loader"
    SECTION_DIFF_ANALYZER = "section_diff_analyzer"
    DRAWING_ANALYZER = "drawing_analyzer"
    RASTER_DRAWING_ANALYZER = "raster_drawing_analyzer"
    IFC_VALIDATOR = "ifc_validator"
    IDS_VALIDATOR = "ids_validator"
    CLASH_DETECTOR = "clash_detector"
    REMARK_GENERATOR = "remark_generator"
    OBJECT_STORE = "object_store"
    AUDIT_REPORT_STORE = "audit_report_store"
    ANALYZE_PROJECT_PACKAGE_JOB_STORE = "analyze_project_package_job_store"
    VALIDATE_IFC_AGAINST_IDS_USE_CASE = "validate_ifc_against_ids_use_case"
    ANALYZE_PROJECT_PACKAGE_USE_CASE = "analyze_project_package_use_case"
    SUBMIT_ANALYZE_PROJECT_PACKAGE_JOB_USE_CASE = "submit_analyze_project_package_job_use_case"
    GET_ANALYZE_PROJECT_PACKAGE_JOB_STATUS_USE_CASE = (
        "get_analyze_project_package_job_status_use_case"
    )
    ANALYZE_PROJECT_PACKAGE_JOB_RUNNER = "analyze_project_package_job_runner"
    EXTERNAL_EVIDENCE_VERIFIER = "external_evidence_verifier"
    IFC_SCHEMA_VALIDATOR = "ifc_schema_validator"
    IDS_DOCUMENT_AUDITOR = "ids_document_auditor"
    BCF_API_CLIENT = "bcf_api_client"
    PUSH_REPORT_TO_BCF_API_USE_CASE = "push_report_to_bcf_api_use_case"
    OIDC_TOKEN_VALIDATOR = "oidc_token_validator"
    BSI_VALIDATION_SERVICE = "bsi_validation_service"
    REVIEW_EVENT_STORE = "review_event_store"
