class Tokens:
    SETTINGS = "settings"
    LOGGER = "logger"
    REQUIREMENT_EXTRACTOR = "requirement_extractor"
    NARRATIVE_RULE_SYNTHESIZER = "narrative_rule_synthesizer"
    DRAWING_ANALYZER = "drawing_analyzer"
    VISION_DRAWING_ANALYZER = "vision_drawing_analyzer"
    IFC_VALIDATOR = "ifc_validator"
    IDS_VALIDATOR = "ids_validator"
    CLASH_DETECTOR = "clash_detector"
    REMARK_GENERATOR = "remark_generator"
    AUDIT_REPORT_STORE = "audit_report_store"
    ANALYZE_PROJECT_PACKAGE_JOB_STORE = "analyze_project_package_job_store"
    VALIDATE_IFC_AGAINST_IDS_USE_CASE = "validate_ifc_against_ids_use_case"
    ANALYZE_PROJECT_PACKAGE_USE_CASE = "analyze_project_package_use_case"
    SUBMIT_ANALYZE_PROJECT_PACKAGE_JOB_USE_CASE = "submit_analyze_project_package_job_use_case"
    GET_ANALYZE_PROJECT_PACKAGE_JOB_STATUS_USE_CASE = "get_analyze_project_package_job_status_use_case"
    ANALYZE_PROJECT_PACKAGE_JOB_RUNNER = "analyze_project_package_job_runner"
