/** Visible Russian chrome. Not a locale product; one pass for the expert seat. */

export const UI_COPY = {
  headerEyebrow: "AeroBIM · оболочка разбора · checkpoint NO_GO",
  headerTitle: "Комплект: модель ↔ листы ↔ ТЗ ↔ расчёты",
  headerLede:
    "Шов комплекта, не замена 10D/Tangl. UI не пишет summary.passed. Native RVT/NWD/DWG — fail-closed. 30:00 — цель ТЗ, не измеренный SLA.",
  roleBanner:
    "Переключатель в шапке — макет экрана, не разграничение доступа. GET /v1/auth/bff = 501 (не OIDC). HITL на сервере: expert/reviewer; user/viewer и общий Bearer → 403.",
  roleSelectLabel: "Макет экрана (не доступ)",
  roleExpert: "Эксперт",
  roleUser: "Пользователь",
  reportsLoaded: (n: number) => `${n} отчёт(ов) загружено`,
  saveRemark: "Сохранить правку",
  savingRemark: "Сохраняем…",
  confirmRemark: "Подтвердить замечание",
  rejectRemark: "Отклонить замечание",
  confirmed: "Подтверждено",
  rejected: "Отклонено",
  remarkSaved: "Записано в review-events",
  remarkSaveFailed: "Не удалось сохранить",
  remarkDecisionFailed: "Решение не записано",
  hitlUserAlias:
    "Макет «Пользователь» — не OIDC. Подтвердить/Отклонить на сервере недоступны этой роли.",
  hitlHistory: "История HITL",
  noEvents: "Нет событий по этой находке.",
  editRemark: "Текст замечания",
  exportPdf: "PDF (черновик покрытия)",
  exportPdfHint: "Простой PDF карты покрытия, не ГОСТ-отчёт и не СОД.",
  xlsxNotMvp: "XLSX нет на MVP",
  presetScope: "Область пресета",
  presetBrowser: "Этот браузер",
  presetFile: "Файл JSON",
  presetName: "Имя пресета",
  savePreset: "Сохранить пресет",
  runKicker: "Прогон",
  runTitle: "Задание анализа",
  runTimer: (mmss: string) => `Таймер: ${mmss} / цель ТЗ 30:00 (не SLA)`,
  runTimerIdle: "Таймер появится после запуска. Цель ТЗ 30:00 на комплект — не измеренный SLA.",
  toExpert: "К эксперту",
  keyboardHelp:
    "J/K или стрелки — следующая/предыдущая находка. A — подтвердить. R — отклонить. E — фокус замечания. ? — эта справка. Esc — закрыть. Только мышью на сотнях находок критерий когнитивной нагрузки не проходит.",
  loadReportsFailed: "Не удалось загрузить список отчётов.",
  loadReportFailed: "Не удалось загрузить отчёт.",
  unspecifiedProject: "Проект не указан",
  emptyReports: "Нет сохранённых отчётов по текущему запросу.",
  loadingReports: "Загружаем отчёты…",
  selectReport: "Выберите отчёт на экране Проекты или Эксперт.",
  searchReports: "Поиск загруженных отчётов",
  filterProject: "Фильтр проекта",
  filterDiscipline: "Фильтр раздела",
  filterStatus: "Фильтр статуса",
  filterProjectPh: "Проект",
  filterDisciplinePh: "Раздел",
  statusAll: "Все статусы",
  statusPassed: "Только pass",
  statusFailed: "Только fail",
  groupByProject: "Группировать по проекту",
  ungroupReports: "Разгруппировать",
  copyShareLink: "Копировать ссылку",
  linkCopied: "Ссылка скопирована",
  copyFailed: "Не скопировалось",
  copyPresets: "Копировать JSON",
  downloadPresets: "Скачать JSON",
  importPresetsFile: "Импорт файла JSON",
  importPresetsJson: "Импорт JSON",
  presetImportPayload: "JSON пресетов",
  presetImportPh: "Вставьте JSON пресетов",
  presetCopied: "JSON скопирован",
  presetDownloaded: "JSON скачан",
  presetImported: "JSON импортирован",
  presetFailed: "Обмен JSON не удался",
  removePreset: (name: string) => `Удалить пресет ${name}`,
  reportListKicker: "Индекс",
  reportListTitle: "Список отчётов",
  reportFilters: "Фильтры списка отчётов",
  presetsAria: "Пресеты фильтров",
  enginePass: "Pass движка",
  engineFail: "Fail движка",
  requestLabel: (id: string) => `Запрос ${id}`,
  issueCount: (n: number) => `${n} находок`,
  syntheticMark: "Синтетический контент (ИИ), не влияет на summary.passed",
  remarkHeading: "Замечание",
  generatedRemark: "Сгенерированное замечание",
  selectIssue: "Выберите находку, чтобы править замечание.",
  historyFailed: "Не удалось загрузить историю HITL",
  findingsKicker: "Находки",
  findingsTitle: "Список замечаний",
  loadingReport: "Загружаем отчёт…",
  noReportSelected: "Отчёт не выбран. Откройте Проекты или git-фикстуру (не пакет заказчика).",
  packSwitcher: "Комплект",
  selectedPack: "Выбранный отчёт комплекта",
  clashKicker: "2D / 3D",
  clashTitle: "Клэши как фокус вьюера",
  selectReportClash: "Выберите сохранённый отчёт, чтобы смотреть пары клэшей.",
  noClash: "В этом отчёте нет payload клэшей.",
  viewerFocusOn: "фокус вьюера",
  focusClash: "фокус на клэш",
  remarkKicker: "Замечание",
  remarkCardTitle: "Карточка и доказательства",
  selectReportFirst: "Сначала выберите отчёт.",
  matchingReqs: "Совпавшие требования",
  noReqMatch:
    "Нет точного совпадения по rule id. Отчёт мог идти по синтезированной или агрегатной логике.",
  noProperty: "нет свойства",
  noExpected: "нет ожидаемого",
  noUnit: "нет единицы",
  noEntity: "Требование без области entity",
  severity: "Серьёзность",
  severityAll: "Все",
  groupFindings: "Группировка",
  groupNone: "Без групп",
  groupRule: "По правилу",
  groupStorey: "По этажу",
  groupAxis: "По оси",
  groupCategory: "По категории",
  hitlOnly: "Только HITL-регионы",
  shownCount: (shown: number, total: number, virtualize: boolean) =>
    `${shown} / ${total} показано${virtualize ? " · оконный список" : ""}`,
  noFindings:
    "Нет находок по фильтру. Нет расчётной записки — арматура не проверялась. Загрузите PDF/Excel ЛИРА на Загрузке.",
  noTarget: "нет цели",
  advisory: "кандидат, advisory",
  deterministic: "deterministic",
  lowConfidence: (n: string) => `низкая уверенность ${n}`,
  uploadKicker: "Загрузка",
  uploadTitle: "Приём файлов",
  uploadHint:
    "Обмен КТ#3: IFC + PDF/A. Office — заявленные поля. Нативные RVT/NWD/DWG/.lir — fail-closed, не тихий skip. 1,5 ГБ модель в браузере не разбираем. Checkpoint NO_GO.",
  dropHint: "Перетащите IFC/PDF/Office или выберите файл. Нативные RVT/NWD/DWG на сервер не уходят.",
  chooseFile: "Выбрать файл",
  packFileUpload: "Файл комплекта",
  uploading: "Загрузка…",
  uploadProgress: "Прогресс загрузки",
  cancelUpload: "Отменить загрузку",
  uploadFailed: "Загрузка не удалась",
  failClosedBefore: (name: string) => `${name}: fail-closed до отправки.`,
  viewerKicker: "Пространственный разбор",
  viewerTitle: "IFC-вьюер",
  viewerLoading: "Загружаем runtime пространственного разбора…",
  viewerNeedReport: "Выберите сохранённый отчёт, чтобы загрузить IFC во вьюер.",
  viewerCaption:
    "Тяжёлый runtime web-ifc подгружается по требованию. Оболочка отчёта остаётся лёгкой.",
  resetView: "Сбросить вид",
  isolateSelected: "Изолировать выбранное",
  showAll: "Показать всё",
  noReportShort: "Отчёт не выбран",
  clashPairMode: "пара клэша",
  issueFocusMode: "фокус находки",
  noSelectionMode: "нет выбора",
  elementN: (n: number) => `элемент ${n}`,
  element: "элемент",
  viewerInit: "Инициализация web-ifc и сцены…",
  viewerLoad: "Загрузка байт IFC и геометрии выбранного отчёта…",
  viewerError: "Вьюер не загрузил выбранный IFC.",
  viewerFooter:
    "Вьюер ниже сохранённого отчёта. Выбор — по GUID находки или пары клэша, не произвольный осмотр модели. prefers-reduced-motion отключает демпфирование орбиты.",
  engineGateway: "Шлюз движка",
  engineFlag: "Технический флаг с сервера. Не подпись эксперта. UI не пишет",
  hitlVerdict: "Вердикт HITL",
  hitlConfirmed: "Подтверждено экспертом",
  hitlRejected: "Отклонено экспертом",
  hitlRecording: "Записываем HITL…",
  hitlNotRecorded: "HITL не записан",
  hitlNone: "Решения эксперта нет",
  hitlSeparate: "Отдельная сущность. ADR-001. Макет роли — не OIDC.",
  navAria: "Экраны рабочего места",
  spatialNone: "Нет пространственного выбора",
  spatialNoneDetail: "Выберите находку с GUID IFC или пару клэша.",
  spatialIssueDetail: (guid: string) => `Фокус на одном элементе по GUID ${guid}.`,
  spatialClashHeading: (type: string) => `${type} · пара клэша`,
  spatialClashDetail: (n: number) => `${n} элемента IFC из активной пары клэша.`,
  evidenceAria: "Уровни доказательства",
  evidencePresent: "есть",
  evidenceMissing: "нет",
  essenceStep: "1 суть",
  sheetStep: "2 лист",
  spatialStep: "3 3D",
  rawStep: "4 сырьё",
  sameOriginApi: "same-origin /v1 (прокси Vite)",
  drawingKicker: "Доказательство 2D",
  drawingTitle: "Наложение зоны",
  selectReportDrawing: "Выберите отчёт, чтобы смотреть наложение на лист.",
  noDrawingAssets: "Для этого отчёта нет сохранённого превью листа.",
  assetNa: "нет актива",
  previewNa: "нет превью",
  overlayTarget: "цель наложения",
  browseMode: "просмотр листа",
  regionOverlays: (n: number) => `${n} наложени(й)`,
  hitlRegions: (n: number) => `${n} HITL-регион(ов)`,
  hitlRegionsAria: "Регионы, требующие эксперта",
  drawingAssetsAria: "Сохранённые листы",
  issueMatch: "совпадение находки",
  drawingAlt: (sheet: string) => `Превью чертежа ${sheet}`,
  drawingPage: (sheet: string, page?: number | null) =>
    page ? `${sheet} · стр. ${page}` : sheet,
  unmatchedSheet: (sheet: string) =>
    `Находка ссылается на ${sheet}, но точного превью листа/страницы нет. Можно листать сохранённые активы отчёта.`,
  activeIssue: "Активная находка",
  noActiveIssue: "Нет активной находки. Выберите строку в списке.",
  provenanceOk: "Provenance полный (finding / source / evidence refs).",
  provenanceGap:
    "Provenance неполный: для подписи нужны finding_id, source_id и непустые evidence_refs.",
} as const;
